"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
export default function Home(){
 const [searches,setSearches]=useState<any[]>([]),[selected,setSelected]=useState<number|null>(null),[results,setResults]=useState<any[]>([]); const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const s=await fetch(`${API}/api/searches`).then(r=>r.json());setSearches(s);if(s.length&&selected===null)setSelected(s[0].id)}
 async function loadResults(id:number){setResults(await fetch(`${API}/api/searches/${id}/results`).then(r=>r.json()))}
 async function run(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch(`${API}/api/searches/${selected}/run`,{method:"POST"});if(!r.ok)throw new Error(await r.text());await loadResults(selected)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function seed(){const body={name:"BCN ↔ Buenos Aires",origin:"BCN",destinations:["EZE","AEP"],departure_from:"2026-11-25",departure_to:"2026-12-09",return_from:"2027-01-02",return_to:"2027-01-10",adults:1,cabin:"economy",max_stops:1,target_price:850,ideal_price:750,max_price:1100};await fetch(`${API}/api/searches`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load()}
 useEffect(()=>{load()},[]);useEffect(()=>{if(selected)loadResults(selected)},[selected]);const best=results[0];
 return <main><h1>✈ Flight Monitor</h1><div className="muted">Búsqueda concurrente, consenso multi-provider y BUY / WATCH / WAIT</div><div className="card hero"><div className="controls"><select value={selected??""} onChange={e=>setSelected(Number(e.target.value))}><option value="">Selecciona una búsqueda</option>{searches.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={run} disabled={busy||!selected}>{busy?"Buscando en paralelo…":"Buscar ahora"}</button>{!searches.length&&<button onClick={seed}>Crear búsqueda BCN–Buenos Aires</button>}</div>{error&&<p className="error">{error}</p>}</div>{best&&<div className="grid"><div className="card"><div className="muted small">MEJOR PRECIO</div><div className="price">€{best.price}</div><div>{best.departure_date} → {best.return_date}</div></div><div className="card"><div className="muted small">RECOMENDACIÓN</div><p><span className={`badge ${best.recommendation?.state}`}>{best.recommendation?.state||"—"}</span></p><div>Score {best.recommendation?.score??"—"} · Conf. {best.recommendation?.confidence??"—"}%</div></div><div className="card"><div className="muted small">CONSENSO</div><div className="price">{best.consensus}%</div><div>{best.providers} proveedor(es)</div></div></div>}<div className="card" style={{marginTop:16,overflowX:"auto"}}><table><thead><tr><th>Fechas</th><th>Destino</th><th>Precio</th><th>Aerolínea</th><th>Escalas</th><th>Providers</th><th>Consenso</th><th>Estado</th></tr></thead><tbody>{results.map(r=><tr key={r.id}><td>{r.departure_date}<br/>{r.return_date}</td><td>{r.destination}</td><td>€{r.price}</td><td>{(r.airlines||[]).join(", ")||"—"}</td><td>{r.stops??"—"}</td><td>{r.providers}</td><td>{r.consensus}%</td><td><span className={`badge ${r.recommendation?.state}`}>{r.recommendation?.state||"—"}</span></td></tr>)}</tbody></table></div></main>
}
