"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
async function read(path:string,options?:RequestInit){const r=await fetch(`${API}/api${path}`,options);if(!r.ok)throw new Error(`Error ${r.status} al consultar el servidor`);return r.json()}
export default function Home(){
 const [searches,setSearches]=useState<any[]>([]),[selected,setSelected]=useState<number|null>(null),[results,setResults]=useState<any[]>([]),[demo,setDemo]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[providers,setProviders]=useState<any[]>([]);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[source,setSource]=useState("real");
 async function load(){const s=await read("/searches");setSearches(s);if(s.length&&selected===null)setSelected(s[0].id)}
 async function loadResults(id:number){const [r,d,h,p]=await Promise.all([read(`/searches/${id}/results`),read(`/searches/${id}/results?source=demo`),read(`/searches/${id}/runs`),read('/providers')]);return {r,d,h,p}}
 function apply(data:any){setResults(data.r);setDemo(data.d);setRuns(data.h);setProviders(data.p)}
 async function run(){if(!selected)return;setBusy(true);setError("");try{await read(`/searches/${selected}/run`,{method:"POST"});apply(await loadResults(selected))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function seed(){try{const body={name:"BCN ↔ Buenos Aires",origin:"BCN",destinations:["EZE","AEP"],departure_from:"2026-11-25",departure_to:"2026-12-09",return_from:"2027-01-02",return_to:"2027-01-10",adults:1,cabin:"economy",max_stops:1,target_price:850,ideal_price:750,max_price:1100};await read('/searches',{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load()}catch(e:any){setError(e.message)}}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 useEffect(()=>{let active=true;setResults([]);setDemo([]);setRuns([]);if(selected){setLoading(true);loadResults(selected).then(data=>{if(active)apply(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})}return ()=>{active=false}},[selected]);
 const best=results[0],latest=runs[0],rows=source==="demo"?demo:results;
 const errors=latest?.details?.provider_errors||{};
 return <main><h1>✈ Flight Monitor</h1><div className="muted">Precios de proveedores y datos de demostración separados</div>
 <div className="card hero"><div className="controls"><select aria-label="Búsqueda" disabled={busy} value={selected??""} onChange={e=>setSelected(Number(e.target.value)||null)}><option value="">Selecciona una búsqueda</option>{searches.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={run} disabled={busy||loading||!selected}>{busy?"Buscando en paralelo…":"Buscar ahora"}</button>{!searches.length&&<button onClick={seed}>Crear búsqueda BCN–Buenos Aires</button>}</div>{error&&<p role="alert" className="error">{error}</p>}</div>
 <section className="card diagnostics"><h2>Estado de los proveedores</h2><div className="controls">{providers.map(p=><span key={p.name} className="provider">{p.name}: {p.enabled?"habilitado":"sin configurar / desactivado"}</span>)}</div>
 {providers.length>0&&!providers.some(p=>p.enabled)&&<p className="notice">No hay proveedores reales habilitados. Las búsquedas generan datos demo para comprobar el funcionamiento.</p>}
 {latest?<><p>Última ejecución: {new Date(latest.started_at).toLocaleString("es-ES")} · {latest.status==="running"?"En curso":`${latest.result_count} resultados recibidos`}{latest.details?.mode==="demo"?" · DEMO":""}</p>{latest.status==="empty"&&<p className="notice">Esta ejecución no devolvió ofertas. Los resultados guardados abajo pueden ser anteriores.</p>}{Object.entries(errors).map(([name,messages]:[string,any])=><p className="error" key={name}>{name}: {String(messages[0]).includes("429")?"HTTP 429: límite de solicitudes o cuota alcanzado.":String(messages[0]).match(/HTTP\s*\d{3}|\b[45]\d{2}\b/)?.[0]||"Error al consultar el proveedor."}</p>)}{Object.entries(latest.details?.provider_usage||{}).map(([name,u]:[string,any])=><p className="muted" key={name}>{name}: {u.requests} consultas de un máximo de {u.limit_per_run}; {u.skipped} combinaciones omitidas por límite o bloqueo.</p>)}</>:<p className="muted">Todavía no hay ejecuciones.</p>}</section>
 <div className="controls tabs"><button aria-pressed={source==="real"} onClick={()=>setSource("real")}>Datos reales</button><button aria-pressed={source==="demo"} onClick={()=>setSource("demo")}>Demostración</button></div>
 {source==="demo"?<p className="notice">DEMO · Precios simulados, sin disponibilidad real. Sirven para comprobar el sistema y no generan alertas de compra.</p>:<p className="muted">Ofertas guardadas de proveedores externos. La fecha de consulta indica su antigüedad; confirma precio y disponibilidad antes de reservar.</p>}
 {source==="real"&&best&&<div className="grid"><div className="card"><div className="muted small">MEJOR PRECIO REAL GUARDADO</div><div className="price">{best.price} {best.currency}</div><div>{best.departure_date} → {best.return_date}</div></div><div className="card"><div className="muted small">RECOMENDACIÓN</div><p><span className={`badge ${best.recommendation?.state}`}>{best.recommendation?.state||"—"}</span></p><div>Score {best.recommendation?.score??"—"} · Conf. {best.recommendation?.confidence??"—"}%</div></div><div className="card"><div className="muted small">CONSENSO</div><div className="price">{best.consensus}%</div><div>{best.providers} proveedor(es)</div></div></div>}
 <div className="card" style={{marginTop:16,overflowX:"auto"}}>{loading?<p>Cargando resultados…</p>:!rows.length?<p>{source==="real"?"No hay ofertas reales guardadas. Consulta el estado de los proveedores o abre Demostración para ver los datos de prueba.":"No hay datos demo guardados. Se generan cuando no hay proveedores reales habilitados."}</p>:<table><thead><tr><th>Origen de datos</th><th>Fechas</th><th>Destino</th><th>Precio</th><th>Aerolínea</th><th>Escalas</th><th>Proveedores</th><th>Consenso</th><th>Estado</th><th>Consultado</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><span className={`badge ${source==="demo"?"DEMO":"REAL"}`}>{source==="demo"?"DEMO":"REAL"}</span></td><td>{r.departure_date}<br/>{r.return_date}</td><td>{r.destination}</td><td>{r.price} {r.currency}</td><td>{(r.airlines||[]).join(", ")||"—"}</td><td>{r.stops??"—"}</td><td>{source==="demo"?"Simulador":r.providers}</td><td>{source==="demo"?"No aplica":`${r.consensus}%`}</td><td><span className={`badge ${r.recommendation?.state}`}>{source==="demo"?"Simulado":r.recommendation?.state||"—"}</span></td><td>{new Date(r.last_seen_at).toLocaleString("es-ES")}</td></tr>)}</tbody></table>}</div></main>
}
