from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None
def upgrade():
    op.create_table("searches",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("origin",sa.String(3),nullable=False),sa.Column("destinations",sa.JSON,nullable=False),sa.Column("departure_from",sa.Date,nullable=False),sa.Column("departure_to",sa.Date,nullable=False),sa.Column("return_from",sa.Date,nullable=False),sa.Column("return_to",sa.Date,nullable=False),sa.Column("adults",sa.Integer,nullable=False,server_default="1"),sa.Column("cabin",sa.String(20),nullable=False,server_default="economy"),sa.Column("max_stops",sa.Integer,nullable=True),sa.Column("target_price",sa.Numeric(10,2),nullable=True),sa.Column("ideal_price",sa.Numeric(10,2),nullable=True),sa.Column("max_price",sa.Numeric(10,2),nullable=True),sa.Column("active",sa.Boolean,nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("search_runs",sa.Column("id",sa.Integer,primary_key=True),sa.Column("search_id",sa.Integer,sa.ForeignKey("searches.id",ondelete="CASCADE"),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("provider_count",sa.Integer,nullable=False,server_default="0"),sa.Column("result_count",sa.Integer,nullable=False,server_default="0"),sa.Column("status",sa.String(20),nullable=False,server_default="running"),sa.Column("details",sa.JSON,nullable=False,server_default="{}"))
    op.create_table("offers",sa.Column("id",sa.Integer,primary_key=True),sa.Column("search_id",sa.Integer,sa.ForeignKey("searches.id",ondelete="CASCADE"),nullable=False),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("origin",sa.String(3),nullable=False),sa.Column("destination",sa.String(3),nullable=False),sa.Column("departure_date",sa.Date,nullable=False),sa.Column("return_date",sa.Date,nullable=False),sa.Column("airlines",sa.JSON,nullable=False),sa.Column("stops",sa.Integer),sa.Column("duration_minutes",sa.Integer),sa.Column("currency",sa.String(3),nullable=False),sa.Column("best_price",sa.Numeric(10,2),nullable=False),sa.Column("median_provider_price",sa.Numeric(10,2)),sa.Column("provider_count",sa.Integer,nullable=False,server_default="1"),sa.Column("consensus_score",sa.Float,nullable=False,server_default="0"),sa.Column("price_level",sa.String(20)),sa.Column("booking_url",sa.Text),sa.Column("last_seen_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("search_id","fingerprint",name="uq_search_offer_fingerprint"))
    op.create_table("price_snapshots",sa.Column("id",sa.Integer,primary_key=True),sa.Column("offer_id",sa.Integer,sa.ForeignKey("offers.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(40),nullable=False),sa.Column("provider_offer_id",sa.String(255)),sa.Column("price",sa.Numeric(10,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("booking_url",sa.Text),sa.Column("raw",sa.JSON,nullable=False),sa.Column("checked_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("recommendations",sa.Column("id",sa.Integer,primary_key=True),sa.Column("offer_id",sa.Integer,sa.ForeignKey("offers.id",ondelete="CASCADE"),nullable=False),sa.Column("state",sa.String(10),nullable=False),sa.Column("score",sa.Float,nullable=False),sa.Column("historical_percentile",sa.Float),sa.Column("confidence",sa.Float,nullable=False),sa.Column("reasons",sa.JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index("ix_offers_search_price","offers",["search_id","best_price"]); op.create_index("ix_snapshots_offer_checked","price_snapshots",["offer_id","checked_at"])
def downgrade():
    op.drop_table("recommendations"); op.drop_table("price_snapshots"); op.drop_table("offers"); op.drop_table("search_runs"); op.drop_table("searches")
